#!/bin/sh

# decode all the WebP files generated by the 'generate_webp.sh' script
# and record memory consumption.
# Then, plot the curves with gnuplot.

out="/tmp/RAM-study"

./ram_test ${out}/lossy/*.webp > LOG0
./ram_test ${out}/lossless/*.webp > LOG1

sort LOG0 -n -k 2 > LOG0_S  # sort by width
sort LOG1 -n -k 5 > LOG1_S  # sort by size

# This gnuplot command will generate the following curves:
#    width_distrib.png
#    size_distrib.png
#    memory_vs_width_lossy.png
#    memory_vs_size_lossless.png
gnuplot < graph.plt
